---
- name: vimrc file
  template: src=etc_vimrc.j2 dest=/etc/vimrc owner=root group=root mode=0644 setype=_default
- name: root bashrc file
  template: src=root_bashrc.j2 dest=/root/.bashrc owner=root group=root mode=0644 setype=_default
