---
- name: install post register script
  template: src=yum_validator.sh.j2 dest=/usr/local/src/yum_validator.sh owner=root group=root mode=0755 setype=_default
- name: running yum validator
  shell: /usr/local/src/yum_validator.sh creates=/usr/local/src/rhsm_broker_install.flg
- name: install broker infrastructure
  shell: /bin/bash "{{ ose_script }}" install_components="broker,named,activemq,datastore" mcollective_password="{{ mcollective_password }}" domain="{{ ose_domain }}" hosts_domain="{{ ose_host_domain }}" named_ip_addr="{{ dnsip }}" broker_hostname="{{ broker_name }}" named_entries="{{ dns_entries }}" valid_gear_sizes="{{ valid_gear_sizes}} " default_gear_capabilities=small openshift_user1="{{ console_user }}" openshift_password1="{{ console_user_password }}" 2>&1 | tee -a "{{ ose_script_log }}"
  args:
    creates: "{{ ose_script_log }}"
