---
# This playbook deploys the whole OSE stack.

- name: apply common configuration to all servers
  hosts: all
  remote_user: "{{ uservar }}"
  roles:
    - common

- name: Install broker componets
  hosts: broker
  remote_user: "{{ uservar }}"
  roles:
    - broker

- name: Install Node componets - Small
  hosts: node-small
  remote_user: "{{ uservar }}"
  vars:
    node_profile: small
  roles:
    -  nodes

- name: Install Node componets - Medium
  hosts: node-medium
  remote_user: "{{ uservar }}"
  vars:
    node_profile: medium
  roles:
    -  nodes

- name: Install Node componets - Large
  hosts: node-large
  remote_user: "{{ uservar }}"
  vars:
    node_profile: large
  roles:
    -  nodes

- name: Install Node componets - xpaas
  hosts: node-xpaas
  remote_user: "{{ uservar }}"
  vars:
    node_profile: xpaas
  roles:
    -  nodes

- name: Broker PostDeploy
  hosts: broker
  remote_user: "{{ uservar }}"
  tasks:
    - include: tasks/broker_postdeploy.yml
##
##
