---
- name: install base packages
  yum: name={{ item }} state=present
  with_items:
    - ntp
    - vim
    - mlocate
- name: setup default services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - ntpd
    - iptables
- name: selinux configuration check
  selinux: policy=targeted state=enforcing
