---
- name: configure controller-manager
  template: src=etc_kubernetes_conrtoller-manager.j2 dest=/etc/kubernetes/controller-manager owner=root group=root mode=0644 setype=_default
- name: configure kube config
  template: src=etc_kubernetes_config.j2 dest=/etc/kubernetes/config owner=root group=root mode=0644 setype=_default
- name: configure apiserver
  template: src=etc_kubernetes_apiserver.j2 dest=/etc/kubernetes/apiserver owner=root group=root mode=0644 setype=_default
- name: flannel config file
  template: src=flannel-config.json.j2 dest=/usr/local/src/flannel-config.json owner=root group=root mode=0644 setype=_default
- name: flannel sysconfig file
  template: src=etc_sysconfig_flanneld.j2 dest=/etc/sysconfig/flanneld owner=root group=root mode=0644 setype=_default
- name: install docker registry key file
  template: src=dr.key.j2 dest=/etc/pki/tls/private/dr.key owner=root group=root mode=0644 setype=_default
- name: install docker registry cert file
  template: src=dr.crt.j2 dest=/etc/pki/tls/certs/dr.crt owner=root group=root mode=0644 setype=_default
- name: create docker cert dir
  file: path="/etc/docker/certs.d/{{ registry }}:5000" state=directory owner=root group=root mode=0755 setype=_default
- name: Copy over cert file
  template: src=dr.crt.j2 dest=/etc/docker/certs.d/{{ registry }}:5000/dr.crt owner=root group=root mode=0644 setype=_default
- name: Copy over flannel init script
  template: src=flannel_init.sh.j2 dest=/usr/local/src/flannel_init.sh owner=root group=root mode=0755 setype=_default
