---
- name: setup kubernetes master services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
- name: configure flannel on etcd
  #uri: url="http://127.0.0.1:4001/v2/keys/coreos.com/network/config" method=PUT status_code=201 HEADER_Content-Type="application/json" body="{{ lookup('file','/usr/local/src/flannel-config.json') }}"
  shell: /usr/bin/curl -L http://127.0.0.1:4001/v2/keys/coreos.com/network/config  -XPUT --data-urlencode value@/usr/local/src/flannel-config.json 
- name: setup flannel service
  service: name=flanneld state=started enabled=yes
