---
- name: setup kubernetes master services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
- name: configure flannel on etcd
  uri: url=http://127.0.0.1:4001/v2/keys/coreos.com/network/config method=PUT body="{{ lookup('file','/usr/local/src/flannel-config.json') }}" status_code=201
- name: setup flannel service
  service: name=flanneld state=started enabled=yes
