---
- name: configure flannel on etcd
  shell: /usr/local/src/flannel_init.sh creates=/usr/local/src/curl.out
- name: setup kubernetes master services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - docker
    - flanneld
