---
# This playbook deploys kubernetes

- name: apply common configuration to all servers
  hosts: all
  remote_user: "{{ uservar }}"
  roles:
    - common

- name: Install registry componets
  hosts: registry
  remote_user: "{{ uservar }}"
  roles:
    - registry

- name: Install master componets
  hosts: master
  remote_user: "{{ uservar }}"
  roles:
    - master

- name: Install minion componets
  hosts: minion
  remote_user: "{{ uservar }}"
  roles:
    - minions

##
##
