---
- name: install mariadb
  yum: name={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-server
- name: setup mariadb service
  service: name=mariadb state=started enabled=yes
- name: network port setup
  firewalld: port=3306/tcp permanent=true state=enabled
  notify: reload firewall
- name: hosts entries for OS1
  template: src=etc_hosts.j2 dest=/etc/hosts owner=root group=root mode=0644 setype=_default
  when: rh_os1_host == "true"
