---
- name: install node repo setup script
  template: src=rhsm_node_reposetup.sh.j2 dest=/usr/local/src/rhsm_node_reposetup.sh owner=root group=root mode=0755 setype=_default
- name: run node repo setup script
  shell: /usr/local/src/rhsm_node_reposetup.sh "{{ node_profile }}"
  args:
    creates: /usr/local/src/rhsm_node_reposetup.flg
